"""empty message

Revision ID: d29dae9020d0
Revises: 
Create Date: 2021-03-13 21:03:33.762317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29dae9020d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movie', 'release_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Movie', 'release_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
